//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Huboh.EntityFramework.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Artists_Albums
    {
        public int artist_AlbumID { get; set; }
        public Nullable<int> albumID { get; set; }
        public Nullable<int> artistID { get; set; }
    
        public virtual Albums Albums { get; set; }
        public virtual Artists Artists { get; set; }
    }
}
