//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Huboh.EntityFramework.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class playlist_song
    {
        public int id { get; set; }
        public Nullable<int> music { get; set; }
        public Nullable<int> playlist { get; set; }
    
        public virtual playlist playlist1 { get; set; }
        public virtual song song { get; set; }
    }
}
